POST http://localhost:3001/products
Content-Type: application/json

{
  "price": 50,
  "image_url": "https://ecubi-live-images.s3.us-east-2.amazonaws.com/604666743deba80011bc7397/variants/604e180c512f9d0012795cc1.jpeg",
  "published": false,
  "stock": 0,
  "name": "Te de Menta Francesa ",
  "description": "Te"
}

###

POST http://localhost:3001/products
Content-Type: application/json

{
}